[[landingContent]]
=== Landing content

The following sections describe the purpose and some logic for SELFIE landing content.  +
As an overview, <<table_content_groups>> contains the most precise use-case descriptions the SELFIE team was able to craft that pertain to URL-14 landing-content "groups". These groups can be seen as building blocks that are used to construct landing-content structured data.

[#table_content_groups,reftext='{table-caption} {counter:table-num}']
.SELFIE landing-content groups, their purpose, and descriptive text.
[cols="20e,20e,70",width="90%",options="header",align="center"]
|===
|*Content Group*|*Purpose*|*Description*

|schema.org properties |discovery; indexing |Statements about the non-information resource using schema.org properties. These have literal values (string, number etc) or structured values (collections of sub-properties that would appear as JSON object or an RDF blank node).
|content properties |discovery; indexing |Statements about the nature of the _information_ resource, e.g. available media types or data profiles.
|representation links |discovery; indexing; integration |Links to other representations of the _same resource_. The representations likely come from a different provider and/or system. These links will be objects/blank nodes rather than simple URI/Ls. The object will include a small set of prefetched properties (schema.org, content or descriptive) from the target resource
|descriptive links |non-information resource description |Links to related non-information resources according to the thing’s place in the world. For example a link could describe a spatial, temporal topological or semantic relationship, a sample’s feature of interest, or a river’s reach’s upstream reach. As such these links use properties defined in our domain ontologies. As with representation links, these links will be objects/blank nodes rather than simple URI/Ls.
|descriptive properties |non-information resource description |Statements about the nature of the non-information resource using domain ontology properties. These have literal values (string, number etc) or structured values (collections of sub-properties that would appear as JSON object or an RDF blank node).
|===

The content groups described in <<table_content_groups>> have been encoded in JSON-LD contexts that can be used as a guide for implementers and by-reference in structured data. These contexts are grouped functionally around indexing, documenting data-resources, describing topological feature associations, and providing simple spatial representations of features.

==== Properties for documenting data resources

https://opengeospatial.github.io/ELFIE/contexts/elfie-2/elf-index.jsonld[`elf-index.jsonld`] is intended for search engine indexing and discovery. It contains properties needed for a general preview of a feature. These were chosen to be compatible with search-engine indexing and to give a complete core set of information about a non-information resource. +

----
{
    "@context": {
        "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
        "schema": "http://schema.org/",
        "skos": "http://www.w3.org/2004/02/skos/core#",
        "name": "schema:name",
        "description": "schema:description",
        "spatialCoverage": "schema:spatialCoverage",
        "geo": "schema:geo",
        "image": "schema:image",
        "subjectOf": "schema:subjectOf",
        "sameAs": "schema:sameAs",
        "note": "skos:note"
    }
}
----

==== Properties for documenting related data.

The https://opengeospatial.github.io/ELFIE/contexts/elfie-2/elf-index.jsonld[`elf-index.jsonld`] context contains a set of properties to be used to document data about a non-information resource. These can be thought of as "pre-fetched" information about an information resource. As described below, these can be used as properties of an "in-band" information resource or properties of a blank node that describes an "out-of-band" information resource. `conformsTo` is included here to be complete but the specifics of their use for interoperability should be the subject of future work. +
These properties are useful for documenting any information resource in structured data whether a feature-representation, associated with a schema:subjectOf or schema:sameAs property, or other related data, associated with a more specific property such as a sampling relationship.  +

----
{
    "@context": {
        "dct": "http://purl.org/dc/terms/",
        "schema": "http://schema.org/",
        "provider": "schema:provider",
        "url": "schema:url",
        "conformsTo": "dct:conformsTo",
        "format": "dct:format",
    }
}
----

As is shown in examples in the <<inBandoutofBand>>, these properties can be used in two ways.  +
An in-band resource might be documented as follows: +

----
{
	"@id": "https://in-band-information-resource",
	"about": {
		"schema:description": "Description of the in-band information resource, see https://schema.org/about."
	},
	"provider": {
		"schema:name": "Name of the provider"
	},
	"conformsTo": "https://identifier-of-conformance-target",
	"format": [
		"mime-type-1",
		"mime-type-2"
	]
}
----

An out-of-band resource might be documented similarly but using a blank node as follows: +

----
{
	"url": "https://out-of-band-information-resource",
	"about": {
		"schema:description": "Description of the out-of-band information resource, see https://schema.org/about."
	},
	"provider": {
		"schema:name": "Name of the provider"
	},
	"conformsTo": "https://identifier-of-conformance-target",
	"format": [
		"mime-type-1",
		"mime-type-2"
	]
}
----

==== Properties for relating non-information resources

In addition to the https://opengeospatial.github.io/ELFIE/contexts/elfie-2/elf-index.jsonld[`elf-index.jsonld`] context, SELFIE participants created a https://opengeospatial.github.io/ELFIE/contexts/elfie-2/sosa.jsonld[`sosa.jsonld`] context which includes a isFeatureOfInterestOf association which can be used to associate observational data with a feature of interest. The following is an extremely minimal example that demonstrates this.

----
{
	"@context": [
		"https://opengeospatial.github.io/ELFIE/contexts/elfie-2/sosa.jsonld",
		"https://opengeospatial.github.io/ELFIE/contexts/elfie-2/elf-data.jsonld"
	],
	"@id": "https://non-information-resource",
	"isFeatureOfInterestOf": {
		"@type": "Observation",
		"hasResult": {
			"url": "https://url-to-retrieve-observation-results"
		}
	}
}
----

https://opengeospatial.github.io/ELFIE/contexts/elfie-2/elf-network.jsonld[`elf-network.jsonld`] is a set of spatial and temporal topological properties that can be used to relate non-information resources in space and time.

----
{
    "@context": {
        "gsp": "hhttp://www.opengis.net/ont/geosparql#",
        "time": "https://www.w3.org/TR/owl-time/",
        "intersects": "gsp:sfIntersects",
        "touches": "gsp:sfTouches",
        "within": "gsp:sfWithin",
        "after": "time:after",
        "before": "time:before",
        "intervalAfter": "time:intervalAfter",
        "intervalBefore": "time:intervalBefore",
        "intervalDuring": "time:intervalDuring"
    }
}
----

Many other contexts based on domain data models were created as part of the SELFIE. These can be seen at the https://opengeospatial.github.io/ELFIE/contexts/elfie-2/[SELFIE contexts web page.]

[[dataContent]]
=== Data content

Resources containing data content are extremely diverse. Examples include but are by no means limited to geospatial feature data whether a feature of interest or a reference feature, monitoring result data, monitoring location data, and related remote sensing data. As described above, such data can be said to be "in-band" or "out-of-band". The former would be a data resource that generally conforms to the system of linked data, GeoJSON, and HTML prescribed by the OGC-W3C Spatial Data on the Web best practices and emerging practices such as is described here. The latter is any other data resource that, while of interest and associated with a non-information resource, does not conform to linked data / semantic web practices. +

The distinction between what is landing content and what is data content depends on the context in which the resource is being accessed. That is, in one context, landing content will be seen as data about a non-information resource; in another context, that same landing content will be used merely as hypermedia and metadata to help choose data content of interest. Because of this, semantic annotation of data will look very similar to landing content except that the URL for a resource that is intended to provide landing content (a URL-14) will not appear in the subject or object of linked data. The URL of a resource that provides data content (a URL-200) must appear in the subject or object of linked data. +

The SELFIE focused most of its efforts on details of landing content and how to link to data content. The actual structure of linked data or way to architect resources that provide data content is assumed to be either status quo or left for future work. The potential for resources to have multiple media-type formats and potentially multiple profiles that map onto certain use cases is of great interest and documentation of alternate formats and media types is supported by the landing-content concepts described here.
