[[propertiresRelations]]
=== Properties / Relations

The logic for selection of relations in SELFIE followed from the more content-focused ELFIE. That logic is described in detail in the https://docs.opengeospatial.org/per/18-097.html[ELFIE engineering report] and on the https://opengeospatial.github.io/ELFIE/json-ld/[ELFIE contexts web page.] To summarize, broad adoption and commonality on the web was the primary driver of selection of relations. Spatial topology, temporal, and monitoring concepts were taken from established OGC and W3C ontologies, and domain concepts were sought from OGC domain feature models (GeoSciML, GWML2, HY_Features). The following lists relations by source with comments for selected relations as necessary.

==== Schema.org:

https://opengeospatial.github.io/ELFIE/contexts/elfie-2/elf-index.jsonld[https://opengeospatial.github.io/ELFIE/contexts/elfie-2/elf-index.jsonld]

* https://schema.org/name[https://schema.org/name]
* https://schema.org/description[https://schema.org/description]
* https://schema.org/geo[https://schema.org/geo]
* https://schema.org/image[https://schema.org/image]
* https://schema.org/subjectOf[https://schema.org/subjectOf]
** Used as a generic association between URI-14s and URL-200s, i.e. between a real world feature identifier and a URL that will provide data about the feature.
* https://schema.org/sameAs[https://schema.org/sameAs]
** Used very infrequently to establish that two resources are the same but available via two URIs. A domain-specific association should almost always be used.
* https://schema.org/provider[https://schema.org/provider]
* https://schema.org/url[https://schema.org/url]

==== Dublin Core:

https://opengeospatial.github.io/ELFIE/contexts/elfie-2/elf-data.jsonld[https://opengeospatial.github.io/ELFIE/contexts/elfie-2/elf-index.jsonld]

* http://purl.org/dc/terms/conformsTo[http://purl.org/dc/terms/conformsTo]
* http://purl.org/dc/terms/format[http://purl.org/dc/terms/format]

==== SKOS: 

https://opengeospatial.github.io/ELFIE/contexts/elfie-2/elf-index.jsonld[https://opengeospatial.github.io/ELFIE/contexts/elfie-2/elf-index.jsonld]

* https://www.w3.org/2009/08/skos-reference/skos.html#note[https://www.w3.org/2009/08/skos-reference/skos.html#note]

==== RDFS:

https://opengeospatial.github.io/ELFIE/contexts/elfie-2/elf-index.jsonld[https://opengeospatial.github.io/ELFIE/contexts/elfie-2/elf-index.jsonld]

* https://www.w3.org/2000/01/rdf-schema#label[https://www.w3.org/2000/01/rdf-schema#label]

==== Geosparql:

https://opengeospatial.github.io/ELFIE/contexts/elfie-2/elf-network.jsonld[https://opengeospatial.github.io/ELFIE/contexts/elfie-2/elf-network.jsonld]

* http://www.opengis.net/ont/geosparql#sfIntersects[http://www.opengis.net/ont/geosparql#sfIntersects]
* http://www.opengis.net/ont/geosparql#sfTouches[http://www.opengis.net/ont/geosparql#sfTouches]
* http://www.opengis.net/ont/geosparql#sfWithin[http://www.opengis.net/ont/geosparql#sfWithin]

==== OWL-time:

https://opengeospatial.github.io/ELFIE/contexts/elfie-2/elf-network.jsonld[https://opengeospatial.github.io/ELFIE/contexts/elfie-2/elf-network.jsonld]

* https://www.w3.org/TR/owl-time/#time:after[https://www.w3.org/TR/owl-time/#time:after]
* https://www.w3.org/TR/owl-time/#time:before[https://www.w3.org/TR/owl-time/#time:before]
* https://www.w3.org/TR/owl-time/#time:intervalAfter[https://www.w3.org/TR/owl-time/#time:intervalAfter]
* https://www.w3.org/TR/owl-time/#time:intervalBefore[https://www.w3.org/TR/owl-time/#time:intervalBefore]
* https://www.w3.org/TR/owl-time/#time:intervalDuring[https://www.w3.org/TR/owl-time/#time:intervalDuring]


=== Domain models Classes / Properties / Relations
In order to use classes and properties (or relations) defined in domain models, the SELFIE project needed minimal ontologies to reference. "Minimal ontologies" means having basic classes and relations (associations) from a model without the constraints and axioms that could otherwise be generated in the process of transforming UML models to OWL ontologies. The focus was on having resolvable names for the classes and properties that are used in simple linked data payloads. The packaging pattern used in organizing UML domain models was also not used in this exercise, i.e. one UML model = one minimal ontology. 

The creation of such minimal ontologies for a specific domain model was realized by using _ShapeChange_ processes for the every package of that model, with rules that kept the minimum creations of classes from FeatureTypes and properties with their range definitions. Since there is no rule (known to the IE participants) that specifically constrains the creation of properties from associations only, a second step was to filter (using Sparql queries) properties by their ranges to keep only ObjectPrpperties that originated from associations in the UML Model. The last step was to merge content from different packages into one simple ontology having one base URI. This exercise was performed on GeoSciML, HY_Features and GWML2 domain models.

While this simplification has its merits with regards to linked data applications, a discussion with OGC-NA about how to push this ontologies behind OGC-NA servers concluded that they cannot be published in this state. These minimal ontologies do not respect The OGC-NA content negotiation and naming policy patterns, which allows having different possible views of domain models. The inclusion of all properties (and not only associations) respecting the packaging and naming pattern as defined following the UML models should be guaranteed before issuing a request for integration in the OGC-NA server. A work is being carried out to capitalize on what have done for the minimal ontologies to have more detailed and well organized ontologies that respect the OGC-NA specifications. This would provide a better way to have resolvable JSON-LD contexts directly from the OGC-NA server.
