=== Domain Use Case Experiment Summaries

These brief summaries of domain-use case are described in greater detail in Appendix A: Domain Use Cases and on the SELFIE Web resources: https://opengeospatial.github.io/ELFIE/[https://opengeospatial.github.io/ELFIE/]. +
These summaries contain the following information:

. Summary of non-information URIs and data included in landing-content.
. Summary of organizational setting: non-information URI curator, data providers, landing-content providers.
. Outcome summary and findings.
==== Internet of Water

https://opengeospatial.github.io/SELFIE/demo/internet_of_water[https://opengeospatial.github.io/SELFIE/demo/internet_of_water] +
The Internet of Water non-profit organization (IoW) and U.S. Geological Survey have partnered to develop a non-information identifier registry using the https://geoconnex.us[https://geoconnex.us] namespace. The system is expected to support URI-14 identifiers, community URL-14 content, and URL-200 persistent identifiers for any water -related data. All content is to be community contributed, with some URI-14 identifiers defined in a community-oriented (https://geoconnex.us/ref/[https://geoconnex.us/ref/]) namespace and others defined in organizationally-oriented namespaces. Landing content in this system will be based around monitoring of aquifers and catchments as well as anthropogenic information related to water use and quality. A system of interlinked hydrographic and hydrogeologic features will provide the environmental feature of interest reference network for monitoring and and related data.

The Internet of Water organization is intended to be an independent "umbrella" organization that provides coordination and integration for interlinked data "hubs". Hub organizations can be non-governmental, state, or federal entities that provide data and consistent, integrated information to the community. The system of hubs is envisioned as building on a broad network of data provider organizations.

As described in Annex A: Domain Use Cases, for SELFIE, this use case has been summarized as an example of a data-index accessed through the lens of a single catchment of around 100 sqkm. At the time of implementation, no URI-14 identifiers existed for hydrologic features in the United States. Creation of place-holder identifiers in this use case led to the realization that URI-14 identifiers and URL-14 content should be defined in a non-organizational space (e.g. https://geoconnex.us/ref[https://geoconnex.us/ref]) such that organizational landing-content and representations can be referenced to shared, community identifiers. *This follows from the fact that no one organization's landing-content should be the preferred or default landing-content for a shared environmental feature.*

This use case found that, in general, the use of URI-14 identifiers and URL-14 landing-content works well and provides the flexibility needed to implement the linked data system described here. For example, URI-14s in the initial https://geoconnex.us[https://geoconnex.us] 303 see-other to an OGC API-Features server at https://info.geoconnex.us[https://info.geoconnex.us]. These redirects are like: https://geoconnex.us/ref/hu02/01[https://geoconnex.us/ref/hu02/01] -> https://info.geoconnex.us/collections/hu02/items/01[https://info.geoconnex.us/collections/hu02/items/01] where the URL-14 uses the OGC API-Features URL pattern. In the future, this can be changed to use another API or another host-root url without breaking the linked data landing content. This flexibility allowed the project to move forward knowing that there is flexibility in how to maintain and retrieve landing content, a much more technically involved and costly activity than maintaining the persistent identifier redirect server.

Federal and state data systems are in various states of modernization and remarkably few provide landing pages for data in line with W3C data on the web best practices. This presents a challenge and an opportunity for a project like the internet of water. The challenge is that there is very little to build on directly and very little prior-work to base current implementations on. From another perspective, this is an opportunity to build this system of identifiers and landing content consistently from the start. For readers of this report, the finding on this front is that this approach is new for most organizations and the community learning curve is very real. An evolutionary and incremental approach will be required to show value and build data networks over time. Leadership of this incremental progression from groups that can act as community-wide integrators is key.

==== GSIP

https://opengeospatial.github.io/SELFIE/demo/gsip[https://opengeospatial.github.io/SELFIE/demo/gsip] +
Live demo : https://geoconnex.ca/gsip/app/index.html[https://geoconnex.ca/gsip/app/index.html] 

Summary of non-information URIs and data included in landing-content.

In Canada, water concerns are shared by several federal and provincial departments. Similarly, in the US, several Federal agencies share responsibility for water data with state and local entities. Some environmental or monitoring features have several identitifiers (same monitoring station registered in federal and provincial databases) or have different definitions depending on the need of the organisation (slightly different delimitations of catchments). 

The pilot is limited to the Champlain Lake watershed on both sides of US and Canada. Both countries have slightly different feature types, due to availability of data. It exposes surface and groundwater environmental features; 

* Catchment delineations
* Stream gauges
* Groundwater and surface water monitoring stations
* Waterbodies (lakes and rivers)
* Waterwells
* Aquifers
* Geologic units

Data is provided mostly by various groups inside Natural Resources Canada (NRCan), Environment and Climate Change Canada (ECCC) and the USGS, but there are some contributions by _Environnement et Lutte contre les changements climatiques Québec_ (provincial department DELCCQ).

While the overall architecture meets the original goal of linking different data representations, the experiment exposed conceptuals gaps in the linkage between URL-200 information resource identifiers and URI-14 non-information resource identifiers. These issues are mostly conceptual and relate to how to deal with the realities of data systems.  

For example, the architecture does not handle features or representations that don’t have persistent identifiers.  One case is the hydrographic network from CHyF (a Canadian Hydrographic Features service and data model) that does not use persistent identifiers between network queries.  While large entities maintain identity, smaller segments (for example streams) might exist only in a specific representation of the dataset. It also does not resolve the problem of referencing an arbitrary collection of things, such as all the segments upstream of a point.  This concept is important for monitoring stations, because this is the monitored feature. This case was solved temporarily by creating a resources identifier that is essentially made of parameters of a spatial query.

For instance, this statement tells that a water well is downstream of a point,  which is used to extract all the segments using an API.

----
<https://geoconnex.ca/id/waterwells/qc.1982_8995_100> 
_:downstreamOf 
<https://geoconnex.ca/id/up_watershed/-73.1138,45.26322>
----

There were also conceptual issues on the separation of what data is returned when a URI-14 non information identifier is dereferenced (URL-14) as opposed to URL-200 representations that are linked to the URL-14 landing content. GSIP takes a minimalist view, where most of the data is in the URL-200 representation, not in the URL-14 landing content. This follows from the use case selected by GSIP which was restricted to linking resources using water feature topology.  Other participants had different use cases which shifted the position of some properties from URL-200 representations to URL-14 landing content.

==== scinfo.nz

==== CeRDI

https://opengeospatial.github.io/SELFIE/demo/CeRDI_VVG[https://opengeospatial.github.io/SELFIE/demo/CeRDI_VVG]

==== BRGM-BLiv

==== LOCI

https://opengeospatial.github.io/SELFIE/demo/loci[https://opengeospatial.github.io/SELFIE/demo/loci]