== Terms and definitions

&#9679; Resource ::

an item of interest in the distributed network of environmental data.

&#9679; Non-Information Resource ::

A real-world or conceptual object of interest that is identified by a Uniform Resource Identifier bound to the HTTP protocol (HTTP URI). 

NOTE: In the context of this document, Non-Information Resources are strictly identified by HTTP URIs. In other contexts, a Non-Information Resource may be identified using other protocols such as Uniform Resource Names.

&#9679; Information Resource ::

A digital resource that can be sent as a message over the internet using a protocol such as HTTP. Located using a Uniform Resource Locator (URL).

&#9679; Information Index Resource :: 

An information resource that provides an index of annotated (metadata) links to information and non-information resources that describe or are related to the non-information resource of interest.

&#9679; Indirect Identifier ::

As defined in the https://www.w3.org/TR/2004/REC-webarch-20041215/#indirect-identification[W3C Architecture of the World Wide Web, Volume 1 Section 2.2.3]. In the context of SELFIE, a URI that would usually be used to identify a digital resource is sometimes used as an indirect identifier of a real world feature.

&#9679; In-band resource ::

An in band resource is one that can provide information according to a given technical architecture. In the context of linked data, an in-band resource can provide html and json-ld/rdf representations. Other representations may also be considered in-band if the specified architecture expects them (GeoJSON for example). In-band resources can extend the linked-data graph.

&#9679; Out-of-band resource ::

An out-of-band resource is one that does not adhere to the technical architecture from which it is found. A resource that can provide observation result graphs, XML, CSV, PNG, PDF and JSON representations but no linked-data representation would be considered out-of-band if linked from a linked-data document. Out-of-band resources can not extend the linked data graph.

&#9679; HyperText Transfer Protocol Uniform Resource Identifier (HTTP URI) ::

An identifier with the potential to be used with the HTTP protocol to dereference (look up) the identified resource.

&#9679; HyperText Transfer Protocol Uniform Resource Locator (HTTP URL) ::

A type of URI that can be used to locate an information resource.

&#9679; Data Resource ::

An information resource providing a representation of a non-information resource.

&#9679; Registry ::

Per https://www.fgdc.gov/standards/organization/FGDC-SWG/meetings/2005/2005-12-20/ISO%2019135.ppt[ISO 19135, Geographic information, Procedures for item registration]: An information system that manages a set of files containing identifiers assigned to items with descriptions of the associated items.

&#9679; Resource Model :: 

A taxonomy and functional description of the system of non-information, index and data resources.

&#9679; Node ::

A source of information about real world features. May be specific to a geospatial or scientific application domain. Acts as a node in a system of linked data providers.

&#9679; Hub ::

An aggregator or indexer of information about real world features. Provides integrated information as landing content derived from a community of nodes.
&#9679; Provider ::

An originating source of data.

&#9679; Resolver ::

A registry system that provides 303 redirection from URI-14s to URL-14. 

NOTE: In general, outside the scope of this document and depending on the intent of a given system, a resolver can be more than a 303 registry system. Broadly It could be any intelligent function that adapts the response of a server to the context of request

&#9679; Landing resource ::

The ‘default’ information resource provided, through a range-14 303 redirect, when a non-information resource’s URI is dereferenced. An abstract thing, the actual information resource returned is based on content negotiation. HTML -> landing page; JSON-LD -> landing data. Assumes constant content in the concrete landing page and data.

&#9679; Landing page ::

Presentation-oriented HTML representation of the landing resource. Resource description data are included as values of HTML tags and as structured data: JSON-LD in an HTML script tag.

&#9679; Landing data ::

Machine-oriented representation of the landing resource. Is the structured data object in the HTML page presented on its own. SELFIE expects the landing data media type to be JSON-LD but others are allowed, encouraged even, (RDF/XML; TTL; GML; GeoJSON etc).

&#9679; Structured data ::

As per Google: https://developers.google.com/search/docs/guides/intro-structured-data

&#9679; URI-14 ::

The HTTP URI identifying a non-information resource. When dereferenced the host will respond with 303 redirect to a URL for an information resource. Content can be negotiated. 

&#9679; URL-14 ::

A URL, provided by the 303 redirect from a non-information resource’s HTTP URI, that locates an information resource. Ideally these are kept hidden (not provided as values for in data) as they shouldn’t be confused with the non-information resources HTTP URI.

&#9679; URL-200 ::

A common or garden URL. So called because the most likely HTTP response code is a ‘200 OK’ with content. It could be the URL for a service request or a file on a file server. Content can be negotiated.

===	Abbreviated terms

* API - Application Programming Interface
* CSV - Comma Separated Values
* CURI - Compact Uniform Resource Identifier
* ELFIE - Environmental Linked Features Interoperability Experiment
* GeoJSON - Geographic Javascript Object Notation
* GML - Geography Markup Language
* GWML2 - Groundwater Markup Language 2
* HTML - HyperText Markup Language
* HTTP URI - HyperText Transfer Protocol
* HY_Features - Surface Hydrologic Features Conceptual Model
* IE - Interoperability Experiment
* JSON - Javascript Object Notation
* JSON-LD - Javascript Object Notation for Linked Data
* OWL - Web Ontology Language
* RDF - Resource Description Format
* SELFIE - Second Environmental Linked Features Interoperability Experiment
* TTL - Terse RDF Triple Language
* URI - Uniform Resource Identifier
* URL - Uniform Resource Locator
* XML - eXtensible Markup Language

