[[ResourceContentModel]]
== Resource / Content Model

Resources are the stuff of the internet. Is _a resource_ 1) its identifier, 2) content retrieved by dereferencing its identifier, or 3) some abstract notion identified by a URI and described by dereferenced content? The problems pursued by SELFIE made the importance of these distinctions clear and, to some extent, found some answers. More often than finding answers, the SELFIE found that the technical baseline pertaining to the problem is rich and relatively un-explored for environmental data use cases. That is to say that given the technical baseline available to the community, implementation and building an understanding of modern technologies should proceed in order to better understand pain points and find where additional complexity really is required vs. where existing technologies can satisfy the real need.

[[w3cResources]]
=== W3C Resources Summary

The SELFIE model for web resources is based on the notion of _information resources_ and _non-information resources_ as defined by the W3C document https://www.w3.org/2001/tag/doc/httpRange-14/2007-08-31/HttpRange-14.html[‘Dereferencing HTTP URIs’]. This summarises the so-called ‘Range-14’ decision that, while unofficial, is useful especially when read in conjunction with https://www.w3.org/TR/cooluris/[‘Cool URIs for the Semantic Web’].

Information resources are the currency of the web - the pages and data served in a digital form to be consumed by web browsers and applications. Non-information resources are the things these information resources may describe (for example people, mountains, or Aristotelian philosophical constructs). For SELFIE, the critical distinction between them is that an information resource has a location (expressed as a URL) while a non-information resource has identity, expressed as an HTTP URI. 

HTTP URIs have two roles: 

. a globally unique identifier that can be presented as an identifier string and matched with other identifier strings to establish sameness; and 
. the location of a resolver that can redirect enquiries to the location of an appropriate information resource. 

Several representative information resources describing given non-information resources may exist. For example, information resources available according to various media-types, ontologies and/or content models (e.g. data quality rules, controlled vocabularies or units of measure) may be available. SELFIE sought to refine the classification of these representative information resources to help data-providers clarify what type of resource they publish providing guidance for implementation of resolvers, catalogs, and data services.

The Environmental Linked Features in S+++<u>+++*ELF*+++</u>+++IE are non-information resources.These can be thought of in the following groups (in the following, all ‘features’ are ‘non-information resources’):

. Domain features - identifiable environmental things in the world. 
. Sampling features - human-created representative samples of domain features. These features exist to provide metadata about how the feature was described and how robust/representative that description is. An information resource describing a domain feature would logically use, link to, or summarize data related to sampling features.
. Semantic resources: the ontologies and vocabularies used to structure and populate the descriptions of domain and sampling features. These are formalized using OWL and RDF.

Each of these groups occupy different meta-levels but can be interlinked. For example, allowing an agent traversing a knowledge graph to move from the description of a domain feature to how that description was obtained (sampling features). The links between the domain and sampling features are described with https://www.w3.org/TR/vocab-ssn/[ontologies such as SOSA]. Given that SELFIE has adopted JSON-LD as its RDF encoding syntax, links to semantic resources are provided via JSON-LD contexts that map JSON keys and types to RDF ontology property and class HTTP URIs.

For SELFIE, nodes in a knowledge graph are non-information resources, and the nodes of most interest are those that identify domain features. Sampling and semantic resources provide metadata that describe those features and organise available knowledge about them. Therefore, the SELFIE knowledge graph describes relationships between non-information resources in the ‘real world’. The links between information resources that describe them +++<u>+++*is an important but separate concern*+++</u>+++. In SELFIE, how to transition from non-information resources in the knowledge graph to those in the web of information resources was an important consideration where further work is needed.

[[ELFIEResources]]
=== ELFIE Resources

At the outset of SELFIE, the team was thinking in terms of a "three-tiered resource model" where "resource" was a thing identified by a URI. The resource model involved "non-information resources", "meta-information resources", and "data-information resources". Conceptually, the "non-information" "meta" and "data" scheme is useful, but the word "resource" is wrong when applied to the terminology of particular technologies (such as HTTP Resources). As such, the team found a need to change its language to more accurately reflect what was found to be useful ways to describe what is actually a set of use-cases that can be described in terms of non-information, metadata, and data.

Everything in this scheme is identified by a HTTP URI. In general, we have three categories that can be described as follows:

. non-digital things that are not information,
. digital things that provide meta-information about non-information things, and
. digital things that are information representing or characterizing other things.

Tier 1. is clear -- there should be URIs that only ever return a 300 series redirect and are identifiers for real-world features. Tier 2. is hard to define precisely. It can only be defined strictly by the application retrieving it rather than by specific characteristics of its content. Tier 3. is clear in most cases but has potential overlap with tier 2 in that some applications may consider metadata about a feature to actually be data representing the feature. Since self describing data always contains metadata, we would expect most if not all of tier 2 to be contained in tier 3. +

If we think about it this way, then tier 2 is a convenience layer to achieve a certain functional goal. In SELFIE, tier 2 is a convenience layer for search-engine crawlers and humans looking for an idea of what a real-world feature is, what it's related to, and if there's interesting data available representing it. +

This should make it clear that resource is the wrong word to describe the distinction being drawn here. It is ok for tier 1, but it breaks down for tier 2 and 3. A single URL may have one or more representations designed to be metadata and one or more representations intended to be data -- each intended for a different use pertaining to the same real-world feature. This is not saying that tier 2 and tier 3 are always to be represented variously based on the same URL -- they very well may be represented as different resources. This technical diversity is what SELFIE sought to enable. +

Consider a typical use case considered by the SELFIE:

____
*_As a Web user, I want to find all the information available for an environmental feature, so I can find what I'm looking for and retrieve it._* +
____

As the project dissected this use case the HTTP-Range 14 (303 redirects), OGC API - Features (html landing pages for features), and schema.org JSON-LD in a `<script>` tag of a landing page were all embraced as useful technical solutions that serve it. None of the above requires alternative resource representations (media types). With an HTML landing page, a human user or crawler designed around natural language and schema.org are satisfied. +

However, the IE recognized the potential to bring structure to data (including semantically enabled data) underlying the landing page content. Going further, the SELFIE was premised on the idea that html landing pages are layered on top of a potentially wide range of data systems that need such a discovery layer. Given this, while not addressed specifically in SELFIE,  alternative media types and content negotiation are expected in a system that the SELFIE model is applied to. However, the complexity and lack of broad implementation made making progress on this front difficult. +

Participants in the IE agreed that they would avoid specifying how to use content negotiation between the "meta" and "data" tiers. Standards for content negotiation by profile are emerging but we have not been able to evaluate them rigorously. Instead, SELFIE was limited to describing how to advertise that multiple content-types are available for a given URL in structured JSON-LD data. The scope and summary architecture are described in <<img_architecture>>.


[#img_architecture,reftext='{figure-caption} {counter:figure-num}']
.Summary of the SELFIE resource / content model showing that there are Non-information resources which 303 redirect to a resource intended to provide "landing content". The distinction between landing-content and data-content is use-case specific and methods for negotiating between the two is left for future work.
image::images/SELFIE_Architecture.svg[width=800,align="center"]

[[inBandoutofBand]]
=== "In band" and "out of band" resources

The idea of "in-band" and "out-of-band" has been brought up as a useful distinction between resource representations that can provide information that is useful to a given application (in-band) and resource representations that are opaque to an application (out-of-band). In reality, there are many bands that correspond to various applications. Here, we define the SELFIE-band which is intended to foster interoperability toward the goals of the IE.

There are three defining characteristics of the SELFIE "band":

. _The resources_: ELFIE is a graph of non-information resources.
. _The access protocol_: The HTTP protocol (with no extensions [perhaps controversial?]) with responses managed according to the range-14 decision.
. _The encoding_: HTML + JSON-LD and JSON-LD in which ELFIE non-information resources are identified, and linked to, using the JSON-LD `@id` key.

A SELFIE resource is recognizable because:


. it has an `@id`;
. it has a format property that includes application/ld+json;
This limited set of criteria covers the important architectural concerns. It implies an 'architectural profile' that encompasses `@id`, `schema:url`, `dct:format`, and `rdfs:label` and therefore basic resource description and linking. 

To illustrate the distinction, consider the following JSON-LD example which has one `schema:sameAs` and one `schema:subjectOf` property for an identified feature: 

----
{
  "@id": "https://feature.id",
  "http://schema.org/sameAs":
  {
      "@id": "https://someresource",
      "http://purl.org/dc/terms/format": "application/ld+json;",
      "http://www.w3.org/2000/01/rdf-schema#label": "A resource that can extend the linked data graph."
  },
  "http://schema.org/subjectOf":
  {
    "http://schema.org/url": "https://blobby",
    "http://purl.org/dc/terms/format": "application/xml;",
    "http://www.w3.org/2000/01/rdf-schema#label": "blobby thing with the feature as its subject"
  }
}
----

Alternatively, when we resolve +`https://feature.id`+ we might get a more limited document that does not include pre-fetched content about +`https://someresource`+:
----
{
  "@id": "https://feature.id",
  "http://schema.org/owl#sameAs":
  {
    "@id": "https://someresource"
  },
  "http://schema.org/subjectOf": {
    "http://schema.org/url": "https://blobby",
    "http://purl.org/dc/terms/format": "application/xml;",
    "http://www.w3.org/2000/01/rdf-schema#label": "blobby thing with the feature as its subject?"
  }
}
----
Which would mean we would need to resolve and interrogate +`https://someresource`+ to retrieve information needed to decide whether it is of interest, which is possible with the "in-band" +`https://someresource`+, and might give us the JSON-LD below, but impossible with the "out-of-band" +`https://blobby`+ which might only return xml or linked data using an unknown ontology.

----
{
  "@id": "https://someresource",
  "http://www.w3.org/2000/01/rdf-schema#label": "A resource that can extend the linked data graph.",
  "http://purl.org/dc/terms/format": "application/ld+json;",
  "http://www.w3.org/2000/01/rdf-schema#seeAlso": "https://someOtherThing"
}
----

Note that we have avoided discussion `@type` and `conformsTo`. Use of these properties, while valuable, introduces complexities that were determined to go beyond the scope SELFIE was able to accomplish.

[[resourceResolutionAlternatives]]
=== Resource Resolution Alternatives

The Range-14 decision, to identify real world features with URIs that HTTP-303 redirect to resources providing information about the real world feature, was accepted by SELFIE. <<img_range14>> illustrates the complete solution.

[#img_range14,reftext='{figure-caption} {counter:figure-num}']
.Complete range-14 resolution behavior.
image::images/SELFIE_fig3.svg[width=500,align="left"]

However, to simplify implementation, some landing resource providers skip the 303 redirect entirely, using a URL for a landing resource as an indirect identifier of a real world feature. <<img_indirect_id>> Illustrates this less complicated, but limited approach.

[#img_indirect_id,reftext='{figure-caption} {counter:figure-num}']
.Indirect identification of a feature where a URL is used as an indirect identifier for a real world feature.
image::images/SELFIE_fig4.svg[width=350,align="left"]

There are two related problems with the indirect identification approach: one technical and one social. Both issues stem from the need to maintain stable identifiers for real world features and very real needs to change URLs to retrieve digital resources. 

The technical issue is related to how URLs are used to drive server behavior. Changes to server software implementation often necessitate changes to URL paths or parameters. The requirement to maintain URL stability is in conflict with this and causes needless complexity for server-implementers. 

Socially, real-world feature identification is a process undertaken by a group of people that is likely not the same as those who implement the server software used to retrieve information about those features. Identification of features may work best with a different URI structure than retrieval of digital information about those features; forcing the two groups of people to reconcile these patterns is an unneeded, complicated, and likely fraught interaction that can be eliminated by separating real world feature identification from information index resource identification.

Adding content negotiation to the discussion of resource resolution, a 303 redirect works fine as long as the client passes the same accept header to the redirect target URL. However, there is a common content negotiation override practice involving URL parameters such as `?f=mime-type` or `?format=mime-type` that may be desirable to have passed along as part  of a 303 redirect. Some SELFIE participants support such mime-type overrides, but additional experimentation will be required to determine if there is a solution that should be recommended for this in general. Note that this says nothing about https://www.w3.org/TR/dx-prof-conneg/[content-negotiation "by profile"], an emerging technique that was decided to be beyond the scope SELFIE would be able to address.

Extending the resource resolution use case to include retrieving representations of a feature introduces additional functions that were the subject of some SELFIE experiments. Two such resolution schemes were tested. One required a client to inspect information index hypermedia and make an additional request for an available representation. The other used media-type content negotiation to return a representation available via that media-type directly from a URL-14 indirect identifier without the client needing to review information index hypermedia. These two schemes are illustrated in <<img_conneg>>. These alternatives are equally valid and further work is needed to determine if one is preferable to the other.

[#img_conneg,reftext='{figure-caption} {counter:figure-num}']
.Hypermedia-driven resource resolution (above) versus content negotiation-driven resource resolution (left). While less complex, the content negotiation-driven approach is limited to implementation on a single domain and requires a significantly more complex resolver implementation.
image::images/SELFIE_fig5.svg[width=600,align="left"]

