[[contexts]]
=== Contexts

The SELFIE evolved several JSON-LD contexts that were initially created for the first ELFIE. IE participants also worked to establish a number of contexts containing UML classes and associations (used as feature types and property associations in RDF/JSON-LD) from domain feature models such as GeoSciML, GWML2 and HY_Features. The content of the SELFIE-contexts is described in the meta-content section below. The purpose of the domain-specific contexts is to provide semantics that describe the basic associations between non-information resources (e.g. upstream/downstream associations) and domain-specific type (e.g. a feature is a water well). In order to ensure the contexts are usable by a broad audience and to foster adoption, the contexts and ontologies that they reference were kept purposefully focused and minimal; including feature types and associations from the normative UML models only.

With regard to style of contexts themselves, IE participants agreed that we should alias only properties and not classes/feature types. Only namespace URI prefixs (e.g. `"schema": "http://schema.org/"`) and property keys (e.g. `"sameAs": "schema:sameAs"`) are aliased. Classes are not, instead they are returned as compact URIs (CURIs) in the JSON documents: `"@type": "gw:GW_HydrogeoUnit"`.

The argument for namespace is very common practice. They simplify documents, making URIs shorter and clearer in documents. For example, `gw:GW_Well` is easier to work with than +`https://www.opengis.net/def/gwml2#GW_Well`+.

The first ELFIE made the decision not to use CURIs for property key names as a simplification to make JSON-LD documents more approachable and limit colons in JSON keywords. https://opengeospatial.github.io/ELFIE/json-ld/[See this description of ELFIE context design for more… context.] The downside of this decision is we lose the ability to distinguish between the use of the same label in different JSON-LD contexts. CURIs disambiguate identical property keys (`schema:comment`; `rdfs:comment`) but this can also be accomplished with longer key aliases (`"schemaComment": "schema:comment"`; `"rdfsComment": "rdfs:comment"`). This workaround will be required very rarely and isn't necessary for classes (`@type` values) as they are property values and not used as JSON keys so problematic characters (like colons) are not a problem. 
