=== Non-information resources

** See https://github.com/opengeospatial/SELFIE/issues/19[#19], https://github.com/opengeospatial/SELFIE/issues/15[#15]
** Don't relate URL-14 URL to URI-14 URI -- only ever reference the URI-14. (#19)
The SELFIE content model, with its loosely-defined non-information, meta, and data tiers, is focused on the nature of a resource and not the structure of the identifier used to dereference the resource. However, there is a need to establish expected behavior when dereferencing URIs for information at each of these three tiers. As discussed in section X, the SELFIE project found that the distinction between meta and data tiers is loose and should be the subject of future work. The IE considered two behaviors between non-information and information resources that provide landing content: 1) A 303 redirect from a URI-14 to a URL-14, and 2) Indirect identification of the non-information resource where the URI-14 and URL-14 are identical. +
The distinction between non-information resources and resources that provide landing-content located with different URIs introduces the potential for confusion. This confusion was anticipated to produce two issues:

. Search engine Indexes of landing content might incorrectly record associations with the URL-14 (a less-permanent information identifier) rather than the URI-14 (a more permanent non-information identifier) that the landing content references. 
. URL-14s that are displayed in a browser URL bar after a 303-redirect could easily get copied and used as an indirect identifier when a URI-14 exists and should be used instead.
SELFIE participants tested the former by exposing a pilot infrastructure to the public internet and found that, as long as landing content references the URI-14, search engine indexes work appropriately. The second issue can be mitigated by placing prominent URI-14s on the html representation of landing content and structure URL-14s in such a way that it is clear that they are not meant to be used as identifiers. +
Indirect identification of URI-14s using URL-14s has been tested by SELFIE participants successfully. It was found that this practice limits flexibility of systems to accommodate multiple agencies and the tight coupling of URI-14 and URL-14 introduces technical challenges for landing content resolution. However, the practice is less complicated from a user perspective and, as long as the URL-14s are stable, is compatible with future decoupling of URI-14 and URL-14 when the separation is needed. These two cases, 303 and 200 response codes to a non information resource identifier, illustrate the flexibility of the SELFIE content model as well as the nature of landing-content as a convenient resource that encodes content relating URI-14s to each other and data resources.

An important recommendation IE participants agreed to is that when a 303-redirect from a URI-14 to URL-14 exists, the *URL-14 should not be referenced in structured data*. This follows from the fact that the URL-14 is a locator for landing content with one and only one subject -- the URI-14. That is, a JSON-LD representation of a URL-14 resource would have one and only one root `@id` that is the URI-14 that the JSON-LD documents. As such, the URL-14 should never appear in a linked data graph as it will never return linked data about itself.