[appendix]
[[XMLSchemaDocuments]]
= XML Schema Documents

(( XML Schema Documents may be relevant to an Engineering Report. ))

The term “XML schema“ means all the XML schema parts having the same XML namespace, usually separated into multiple XML Schema Document files (with the file type “.xsd“. The XML schema parts in one XML namespace are usually separated into multiple XML Schema Documents to ease human understanding.

In addition to this document, this report includes several XML Schema Documents. These XML Schema Documents are bundled in a zip file with the present document.

The TBD abilities now specified in this document use TBD specified XML Schema Documents included in the zip file with this document. These XML Schema Documents combine the XML schema fragments listed in various subclauses of this document, eliminating duplications.

These XML Schema Documents roughly match the TBD UML packages described in Annex B, and are named:

    TBD.xsd
    TBD.xsd

These XML Schema Documents use and build on the OWS common XML Schema Documents specified [OGC 06-121r3], named:

    ows19115subset.xsd
    owsCommon.xsd
    owsDataIdentification.xsd
    owsExceptionReport.xsd
    owsGetCapabilities.xsd
    owsOperationsMetadata.xsd
    owsServiceIdentification.xsd
    owsServiceProvider.xsd

All these XML Schema Documents contain documentation of the meaning of each element and attribute, and this documentation shall be considered normative as specified in Subclause 11.6.3 of [OGC 06-121r9].

.GetCapabilities.xsd
[source,xml]
----
<ows:Operation name="GetCapabilities">
  <ows:DCP>
    <ows:HTTP>
      <ows:Post xlink:href="http://www.opengis.net/?">
        <ows:Constraint name="PostEncoding">
          <allowedValues>
            <ows:Value>SOAP</ows:Value>
          </ows:AllowedValues>
        </ows:Constraint>
      </ows:Post>
    </ows:HTTP>
  </ows:DCP>
</ows:Operation>
<ows:Operation name="GetTile">
  <ows:DCP>
    <ows:HTTP>
      <ows:Post xlink:href="http://www.opengis.net/?">
        <ows:Constraint name="PostEncoding">
          <ows:AllowedValues>
            <ows:Value>SOAP</ows:Value>
          </ows:AllowedValues>
        </ows:Constraint>
      </ows:Post>
    </ows:HTTP>
  </ows:DCP>
</ows:Operation>
----
